/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as InviteCodeRouteImport } from './routes/invite_.$code'
import { Route as DashboardSubscriptionRouteImport } from './routes/dashboard/subscription'
import { Route as DashboardSubmitPluginRouteImport } from './routes/dashboard/submit-plugin'
import { Route as DashboardStaffRouteImport } from './routes/dashboard/staff'
import { Route as DashboardServersRouteImport } from './routes/dashboard/servers'
import { Route as DashboardOperatorsRouteImport } from './routes/dashboard/operators'
import { Route as DashboardMediaControlRouteImport } from './routes/dashboard/media-control'
import { Route as DashboardMediaRouteImport } from './routes/dashboard/media'
import { Route as DashboardLogsRouteImport } from './routes/dashboard/logs'
import { Route as DashboardHealthRouteImport } from './routes/dashboard/health'
import { Route as DashboardFinancialsRouteImport } from './routes/dashboard/financials'
import { Route as DashboardDevicesRouteImport } from './routes/dashboard/devices'
import { Route as DashboardControlPlaneRouteImport } from './routes/dashboard/control-plane'
import { Route as DashboardClaimRouteImport } from './routes/dashboard/claim'
import { Route as DashboardAccountsRouteImport } from './routes/dashboard/accounts'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as DashboardServersServerIdRouteImport } from './routes/dashboard/servers_.$serverId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite_/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSubscriptionRoute = DashboardSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubmitPluginRoute = DashboardSubmitPluginRouteImport.update({
  id: '/submit-plugin',
  path: '/submit-plugin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStaffRoute = DashboardStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServersRoute = DashboardServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOperatorsRoute = DashboardOperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMediaControlRoute = DashboardMediaControlRouteImport.update({
  id: '/media-control',
  path: '/media-control',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMediaRoute = DashboardMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHealthRoute = DashboardHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinancialsRoute = DashboardFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevicesRoute = DashboardDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardControlPlaneRoute = DashboardControlPlaneRouteImport.update({
  id: '/control-plane',
  path: '/control-plane',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClaimRoute = DashboardClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountsRoute = DashboardAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardServersServerIdRoute =
  DashboardServersServerIdRouteImport.update({
    id: '/servers_/$serverId',
    path: '/servers/$serverId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/claim': typeof DashboardClaimRoute
  '/dashboard/control-plane': typeof DashboardControlPlaneRoute
  '/dashboard/devices': typeof DashboardDevicesRoute
  '/dashboard/financials': typeof DashboardFinancialsRoute
  '/dashboard/health': typeof DashboardHealthRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/media-control': typeof DashboardMediaControlRoute
  '/dashboard/operators': typeof DashboardOperatorsRoute
  '/dashboard/servers': typeof DashboardServersRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/submit-plugin': typeof DashboardSubmitPluginRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/invite/$code': typeof InviteCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/servers/$serverId': typeof DashboardServersServerIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/claim': typeof DashboardClaimRoute
  '/dashboard/control-plane': typeof DashboardControlPlaneRoute
  '/dashboard/devices': typeof DashboardDevicesRoute
  '/dashboard/financials': typeof DashboardFinancialsRoute
  '/dashboard/health': typeof DashboardHealthRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/media-control': typeof DashboardMediaControlRoute
  '/dashboard/operators': typeof DashboardOperatorsRoute
  '/dashboard/servers': typeof DashboardServersRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/submit-plugin': typeof DashboardSubmitPluginRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/invite/$code': typeof InviteCodeRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/servers/$serverId': typeof DashboardServersServerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/claim': typeof DashboardClaimRoute
  '/dashboard/control-plane': typeof DashboardControlPlaneRoute
  '/dashboard/devices': typeof DashboardDevicesRoute
  '/dashboard/financials': typeof DashboardFinancialsRoute
  '/dashboard/health': typeof DashboardHealthRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/media': typeof DashboardMediaRoute
  '/dashboard/media-control': typeof DashboardMediaControlRoute
  '/dashboard/operators': typeof DashboardOperatorsRoute
  '/dashboard/servers': typeof DashboardServersRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/submit-plugin': typeof DashboardSubmitPluginRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/invite_/$code': typeof InviteCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/servers_/$serverId': typeof DashboardServersServerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/auth/callback'
    | '/dashboard/account'
    | '/dashboard/accounts'
    | '/dashboard/claim'
    | '/dashboard/control-plane'
    | '/dashboard/devices'
    | '/dashboard/financials'
    | '/dashboard/health'
    | '/dashboard/logs'
    | '/dashboard/media'
    | '/dashboard/media-control'
    | '/dashboard/operators'
    | '/dashboard/servers'
    | '/dashboard/staff'
    | '/dashboard/submit-plugin'
    | '/dashboard/subscription'
    | '/invite/$code'
    | '/dashboard/'
    | '/dashboard/servers/$serverId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/auth/callback'
    | '/dashboard/account'
    | '/dashboard/accounts'
    | '/dashboard/claim'
    | '/dashboard/control-plane'
    | '/dashboard/devices'
    | '/dashboard/financials'
    | '/dashboard/health'
    | '/dashboard/logs'
    | '/dashboard/media'
    | '/dashboard/media-control'
    | '/dashboard/operators'
    | '/dashboard/servers'
    | '/dashboard/staff'
    | '/dashboard/submit-plugin'
    | '/dashboard/subscription'
    | '/invite/$code'
    | '/dashboard'
    | '/dashboard/servers/$serverId'
  id:
    | '__root__'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/auth/callback'
    | '/dashboard/account'
    | '/dashboard/accounts'
    | '/dashboard/claim'
    | '/dashboard/control-plane'
    | '/dashboard/devices'
    | '/dashboard/financials'
    | '/dashboard/health'
    | '/dashboard/logs'
    | '/dashboard/media'
    | '/dashboard/media-control'
    | '/dashboard/operators'
    | '/dashboard/servers'
    | '/dashboard/staff'
    | '/dashboard/submit-plugin'
    | '/dashboard/subscription'
    | '/invite_/$code'
    | '/dashboard/'
    | '/dashboard/servers_/$serverId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  InviteCodeRoute: typeof InviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/invite_/$code': {
      id: '/invite_/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/subscription': {
      id: '/dashboard/subscription'
      path: '/subscription'
      fullPath: '/dashboard/subscription'
      preLoaderRoute: typeof DashboardSubscriptionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/submit-plugin': {
      id: '/dashboard/submit-plugin'
      path: '/submit-plugin'
      fullPath: '/dashboard/submit-plugin'
      preLoaderRoute: typeof DashboardSubmitPluginRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/staff': {
      id: '/dashboard/staff'
      path: '/staff'
      fullPath: '/dashboard/staff'
      preLoaderRoute: typeof DashboardStaffRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/servers': {
      id: '/dashboard/servers'
      path: '/servers'
      fullPath: '/dashboard/servers'
      preLoaderRoute: typeof DashboardServersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/operators': {
      id: '/dashboard/operators'
      path: '/operators'
      fullPath: '/dashboard/operators'
      preLoaderRoute: typeof DashboardOperatorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/media-control': {
      id: '/dashboard/media-control'
      path: '/media-control'
      fullPath: '/dashboard/media-control'
      preLoaderRoute: typeof DashboardMediaControlRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/media': {
      id: '/dashboard/media'
      path: '/media'
      fullPath: '/dashboard/media'
      preLoaderRoute: typeof DashboardMediaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/health': {
      id: '/dashboard/health'
      path: '/health'
      fullPath: '/dashboard/health'
      preLoaderRoute: typeof DashboardHealthRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/financials': {
      id: '/dashboard/financials'
      path: '/financials'
      fullPath: '/dashboard/financials'
      preLoaderRoute: typeof DashboardFinancialsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/devices': {
      id: '/dashboard/devices'
      path: '/devices'
      fullPath: '/dashboard/devices'
      preLoaderRoute: typeof DashboardDevicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/control-plane': {
      id: '/dashboard/control-plane'
      path: '/control-plane'
      fullPath: '/dashboard/control-plane'
      preLoaderRoute: typeof DashboardControlPlaneRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/claim': {
      id: '/dashboard/claim'
      path: '/claim'
      fullPath: '/dashboard/claim'
      preLoaderRoute: typeof DashboardClaimRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accounts': {
      id: '/dashboard/accounts'
      path: '/accounts'
      fullPath: '/dashboard/accounts'
      preLoaderRoute: typeof DashboardAccountsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/servers_/$serverId': {
      id: '/dashboard/servers_/$serverId'
      path: '/servers/$serverId'
      fullPath: '/dashboard/servers/$serverId'
      preLoaderRoute: typeof DashboardServersServerIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAccountsRoute: typeof DashboardAccountsRoute
  DashboardClaimRoute: typeof DashboardClaimRoute
  DashboardControlPlaneRoute: typeof DashboardControlPlaneRoute
  DashboardDevicesRoute: typeof DashboardDevicesRoute
  DashboardFinancialsRoute: typeof DashboardFinancialsRoute
  DashboardHealthRoute: typeof DashboardHealthRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardMediaRoute: typeof DashboardMediaRoute
  DashboardMediaControlRoute: typeof DashboardMediaControlRoute
  DashboardOperatorsRoute: typeof DashboardOperatorsRoute
  DashboardServersRoute: typeof DashboardServersRoute
  DashboardStaffRoute: typeof DashboardStaffRoute
  DashboardSubmitPluginRoute: typeof DashboardSubmitPluginRoute
  DashboardSubscriptionRoute: typeof DashboardSubscriptionRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardServersServerIdRoute: typeof DashboardServersServerIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAccountsRoute: DashboardAccountsRoute,
  DashboardClaimRoute: DashboardClaimRoute,
  DashboardControlPlaneRoute: DashboardControlPlaneRoute,
  DashboardDevicesRoute: DashboardDevicesRoute,
  DashboardFinancialsRoute: DashboardFinancialsRoute,
  DashboardHealthRoute: DashboardHealthRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardMediaRoute: DashboardMediaRoute,
  DashboardMediaControlRoute: DashboardMediaControlRoute,
  DashboardOperatorsRoute: DashboardOperatorsRoute,
  DashboardServersRoute: DashboardServersRoute,
  DashboardStaffRoute: DashboardStaffRoute,
  DashboardSubmitPluginRoute: DashboardSubmitPluginRoute,
  DashboardSubscriptionRoute: DashboardSubscriptionRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardServersServerIdRoute: DashboardServersServerIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  InviteCodeRoute: InviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
